#!/usr/local/bin/bash

_IDX=0

for _REP in $(ls -1d ../* | grep -v github.io)
do
	_REPO="$(basename "$_REP")"			# Learning-TypeScript_DataStructures-and-Algorithms-01
	_TEMP="${_REPO%%_*}"				# Learning-TypeScript

	if [[ "$_TEMP" == "$_REP" ]]; then
		_SUBTITLE="$_TEMP"
	else
		_SUBTITLE="${_REPO#*_}"				# DataStructures-and-Algorithms-01
		_SUBTITLE="${_SUBTITLE/-/ }"			# DataStructures and Algorithms 01
		_TYPE="${_TEMP%%-*}"
		_LANG="${_TEMP#*-}"

		if [[ "$_TYPE" = "$_LANG" ]]; then
			_LANG=""
			_TITLE="$_TYPE"
		else
			_TITLE="$_TYPE $_LANG"
		fi
	fi

	[[ "$_LANG" = ""	]] && _LANG=default

	_CATEGORY="${_TYPE,,}"

	[[ "$_CATEGORY" =~ "learning"	]] && _CATEGORY=learn
	[[ "$_CATEGORY" =~ "koans"		]] && _CATEGORY=test
	[[ "$_CATEGORY" =~ "course"		]] && _CATEGORY=practice

	echo "- title: \"$_TITLE\""
	echo "  subtitle: \"$_SUBTITLE\""
	echo "  link: https://github.com/ionic-toolbox/$_REPO"
	echo "  lang: $_LANG"
	echo "  img: ${_LANG,,}.png"
	echo "  category: ${_CATEGORY,,}"
	echo ""
	echo "#"

done | tee _data/repositories.yml | grep 'link:'
