#!/bin/bash

#rm -rf TMP
#git clone -q git@github.com:jekyll-toolbox/TEMPLATE.github.io.git TMP
for _F in run_build run_serve run_setup_links Makefile
do
	_F=${_F#*/}
	printf "%-16s %s\n" "${_F}" "-----------------------------------------------------"
	diff $_F TMP/$_F
done
