#!/usr/local/bin/bash

_CLOUD=/Users/Shared/CLOUD/

USERID="$(basename $(pwd))"

_DIRGIT=$_CLOUD/Development.GitHub/img.github.io
_DIRIMG=../${USERID}/assets/img

for _REP in $(ls -1d ../* | grep -v github.io)
do
	_REPO="$(basename "$_REP")"			# Learning-TypeScript_DataStructures-and-Algorithms-01
	_TEMP="${_REPO%%_*}"				# Learning-TypeScript

	if [[ "$_TEMP" == "$_REP" ]]; then
		_SUBTITLE="$_TEMP"
	else
		_SUBTITLE="${_REPO#*_}"				# DataStructures-and-Algorithms-01
		_SUBTITLE="${_SUBTITLE/-/ }"			# DataStructures and Algorithms 01
		_TYPE="${_TEMP%%-*}"
		_LANG="${_TEMP#*-}"

		if [[ "$_TYPE" = "$_LANG" ]]; then
			_LANG=""
			_TITLE="$_TYPE"
		else
			_TITLE="$_TYPE $_LANG"
		fi
	fi

	_IMG="${_SUBTITLE/ /-}.png"
	_IMG="${_IMG,,}"
	
	if   [[ -f "$_DIRIMG/$_IMG" ]]; then
		:
	elif [[ -f $_DIRGIT/$_IMG ]]; then
		cp "$_DIRGIT/$_IMG" "$_DIRIMG"
	else
		_IMG="${_TITLE/ /-}.png"
		_IMG="${_IMG,,}"

		if   [[ -f "$_DIRIMG/$_IMG" ]]; then
			:
		elif [[ -f $_DIRGIT/$_IMG ]]; then
			cp "$_DIRGIT/$_IMG" "$_DIRIMG"
		fi
	fi
	
	[[ "$_LANG" = ""	]] && _LANG=default

	_CATEGORY="${_TYPE,,}"

	[[ "$_CATEGORY" =~ "learning"	]] && _CATEGORY=learn
	[[ "$_CATEGORY" =~ "koans"		]] && _CATEGORY=test
	[[ "$_CATEGORY" =~ "course"		]] && _CATEGORY=practice

	echo "- title: \"$_TITLE\""
	echo "  subtitle: \"$_SUBTITLE\""
	echo "  link: https://github.com/${USERID}/$_REPO"
	echo "  lang: $_LANG"
	echo "  img: ${_IMG}"
	echo "  category: ${_CATEGORY,,}"
	echo ""
	echo "#"

done | tee _data/repositories.yml | grep 'link:'
