#!/usr/local/bin/bash

#set -u

_LINK_GITHUB=https://github.com

_USER="$(basename "$(dirname "$PWD")")"
_HERE="$(cd ..; pwd)"

_FLDR_CLOUD=/Users/Shared/CLOUD
_FLDR_GIT=$_FLDR_CLOUD/Development.Resources/img.github.io
_FLDR_IMG=../${_USER}.github.io/assets/img

LOGL=2
LOGPOS=10
LOG() {
	local _LOGL; _LOGL="$1";	shift
	local _PAR1; _PAR1="$1"; 	shift
	local _PAR2; _PAR2="$*"

	(( LOGPOS = $LOGPOS + 1))

	if  [[ $_LOGL -le $LOGL ]]; then
		printf "# %4s: %-10s =%s\n" "$LOGPOS" "$_PAR1" "$_PAR2"
		printf "# %4s: %-10s =%s\n" "$LOGPOS" "$_PAR1" "$_PAR2" >&2
	fi
}

LOG_NEWLINE() {
	if  [[ $LOGL -gt 2 ]]; then
		printf "\n" >&2
	fi
}
ADD() {
	local _PAR1; _PAR1="${1}";
	local _PAR2; _PAR2="${2:- }"

	echo "${_PAR1} ${_PAR2}"
}

LOG 1 "Scanning repositories" "$_HERE"

for _THISREP in $(ls -1dF ../* | grep -v -E 'github.io|bin' | grep -E '[\@/]$' | sort)
do
	LOGPOS=0

	LOG_NEWLINE
	LOG 2 "REPO" "$_THISREP"

	_STEP=""
	_REPO="$(basename "$_THISREP" | tr -d '@')"

	_TEMP="${_HERE}/${_REPO}"
	if [[ -h "${_TEMP}" ]]; then
		_TEMP="$(readlink "${_TEMP}")"

		# basename
		_REPO="${_TEMP##*/}"

		# dirname
		_TEMP="${_TEMP%/*}"
		_USER="${_TEMP##*/}"
	fi
	LOG 3 "TEMP" "$_TEMP"

	_TEMP="${_REPO%%_*}"							# Learning-TypeScript

	LOG 3 "HERE" "$_HERE"
	LOG 3 "REPO" "$_REPO"
	LOG 3 "TEMP" "$_TEMP"
	LOG 3 "USER" "$_USER"

	_REALPATH="$(readlink "$_THISREP")"
	_REALPATH="${_REALPATH#*repositories/}"
	LOG 3 "PATH" "$_REALPATH"

	if [[ "$_REALPATH" = "" ]]; then
		_STEP="U1"
		_THISUSR="$_USER"
	else
		_STEP="U2"
		_THISUSR="$(dirname "$_REALPATH")"
	fi
	LOG 3 "THISUSR" "$_THISUSR"

	_LINK="$_LINK_GITHUB/$_THISUSR/$_REPO"
	LOG 3 "LINK" "$_LINK"

	if [[ -f "$_THISREP/DESCRIPTION" ]]; then
		_STEP="${_STEP}-T1"
		_TEXT=$(cat "$_THISREP/DESCRIPTION" | sed '1,$s/$/\<br\>/g')
	else
		_STEP="${_STEP}-T2"
		_TEXT=""
	fi
	LOG 3 "TEXT" "$_TEXT"

	_TITLE="missing"
	_LANG="-"
	_IMAGE="placeholder.png"

	_CATEGORY="${_TEMP,,}"
	LOG 3 "CATEGORY" "$_CATEGORY"

	LOG 3 "CHECK" "$_TEMP / $_REPO"
	if [[ "$_TEMP" == "$_REPO" ]]; then
		_STEP="${_STEP}-S1"

		LOG 3 "SAME" "$_TEMP / $_REPO"
		_SUBTITLE="$_TEMP"
	else
		_STEP="${_STEP}-S2"

		_SUBTITLE="${_REPO#*_}"			# DataStructures-and-Algorithms-01
		_SUBTITLE="${_SUBTITLE//-/ }"	# DataStructures and Algorithms 01

		_TYPE="${_TEMP%%-*}"
		_LANG="${_TEMP#*-}"
		_LANG="${_LANG,,}"

		LOG 3 "SUBTITLE" "$_SUBTITLE"
		LOG 3 "TYPE"     "$_TYPE"
		LOG 3 "LANG"     "$_LANG"

		if [[ "${_LANG}" == "${_TYPE,,}" ]]; then
			_LANG=""
			_STEP="${_STEP}-L1"
		else
			_STEP="${_STEP}-L#"
		fi

		LOG 3 "LANG" "$_LANG"

		if [[ "$_TYPE" = "$_LANG" ]]; then
			_TITLE="$_TYPE"
			LOG 3 "TITLE" "$_TITLE"

			_STEP="${_STEP}-T1"
		else
			_TITLE="$_TYPE $_LANG"
			LOG 3 "TITLE" "$_TITLE"

			_STEP="${_STEP}-T2"
		fi

		[[ "$_CATEGORY" =~ "missing"	]] && _CATEGORY=missing
		[[ "$_CATEGORY" =~ "learning"	]] && _CATEGORY=learn
		[[ "$_CATEGORY" =~ "awesome"	]] && _CATEGORY=learn
		[[ "$_CATEGORY" =~ "koans"		]] && _CATEGORY=test
		[[ "$_CATEGORY" =~ "course"		]] && _CATEGORY=practice
		[[ "$_CATEGORY" =~ "workshop"	]] && _CATEGORY=practice

		LOG 3 "CATEGORY/IM" "$_CATEGORY / $_IMAGE"
	fi

    _IMAGE="${_SUBTITLE/ /-}.png"
    _IMAGE="${_IMAGE,,}"

	LOG 3 "check image" "$_FLDR_IMG/$_IMAGE"
	if   [[ -f "$_FLDR_IMG/$_IMAGE" ]]; then
		LOG 3 "use existing image" "$_FLDR_IMG/$_IMAGE"

		_STEP="${_STEP}-I1"
	elif [[ -f "$_FLDR_GIT/$_IMAGE" ]]; then
		cp "$_FLDR_GIT/$_IMAGE" "$_FLDR_IMG"
		LOG 3 "copy master image" "$_FLDR_GIT/$_IMAGE"

		_STEP="${_STEP}-I2"
	else
		_IMAGE="${_CATEGORY/ /-}.png"
		_IMAGE="${_IMAGE,,}"
		LOG 3 "check new image" "$_FLDR_IMG/$_IMAGE"

		if   [[ -f "$_FLDR_IMG/$_IMAGE" ]]; then
			LOG 3 "use new existing image" "$_FLDR_IMG/$_IMAGE"

			_STEP="${_STEP}-I3"
		elif [[ -f "$_FLDR_GIT/$_IMAGE" ]]; then
			LOG 1 "copy master image" "$_FLDR_GIT/$_IMAGE $_FLDR_IMG"
			cp "$_FLDR_GIT/$_IMAGE" "$_FLDR_IMG"

			_STEP="${_STEP}-I4"
		else
			_STEP="${_STEP}-I#"
		fi
	fi

	if   [[ -f "$_FLDR_IMG/$_IMAGE" ]]; then
		_STEP="${_STEP}-M#"
	else
		_IMAGE="placeholder.png"

		_STEP="${_STEP}-M1"
	fi

	if [[ "$_TITLE" == "missing" ]]; then
		_TITLE="$_SUBTITLE"
		_SUBTITLE=""

		_STEP="${_STEP}-T1"
	else
		_STEP="${_STEP}-T#"

	fi

	_TITLE="${_TITLE/css/CSS}"
	_TITLE="${_TITLE/html/HTML}"
	_TITLE="${_TITLE/javascript/Javascript}"
	_TITLE="${_TITLE/typescript/Typescript}"
	_TITLE="${_TITLE/ionic/Ionic}"
	_TITLE="${_TITLE/angular/Angular}"
	_TITLE="${_TITLE/docker/Docker}"
	_TITLE="${_TITLE/jenkins/Jenkins}"
	_TITLE="${_TITLE/python/Python}"
	_TITLE="${_TITLE/ math/ Math}"

	LOG 3 "TITLE" "$_TITLE"
	LOG 3 "STEP"  "$_STEP"

	ADD "- title:"		"\"$_TITLE\""
	ADD "  subtitle:"	"\"$_SUBTITLE\""
	ADD "  text:"		"\"$_TEXT\""
	ADD "  link:"		"\"$_LINK\""
	ADD "  lang:"		"\"$_LANG\""
	ADD "  img:"		"\"${_IMAGE,,}\""
	ADD "  rep:"		"\"${_THISREP/\.\.\//}\""
	ADD "  category:"	"\"${_CATEGORY}\""
	ADD "  step:"		"\"${_STEP}\""
	echo ""
	echo "#"

done | grep -v -E '^#' | cat > _data/repositories.yml
