#!/usr/local/bin/bash

CLOUD=/Users/Shared/CLOUD

# remove already present links
find . -type l -maxdepth 1 -exec rm {} \;

# find directories
for _P in	Enrichment:enrichment-toolbox			\
			Ionic:ionic-training					\
			Ionic:ionic-toolbox						\
			Angular:angular-toolbox					\
			AngularJS:angularjs-toolbox				\
			CSS:css-toolbox							\
			HTML:html-toolbox						\
#			Bootstrap:bootstrap-toolbox
do
	_D=${_P%:*}
	_U=${_P#*:}

	_DIR=$CLOUD/Development.Github/Repositories.FromGithub/repositories/${_U}
	#printf "_P=%-20s _D=%-20s _U=%-20s %s\n" "$_P" "$_D ""$_U" "$_DIR"

	#echo "# 00 Find all repositories in $_DIR"

	find "$_DIR" -type d -mindepth 1 -maxdepth 1 	|\
	grep -v .env					|\
	grep -v .github.io				|\
	while read _R
	do
		_SRC="$_R"
		_DST="$(basename $_SRC)"

		#echo "# 00 _SRC= "$_SRC")"
		#echo "# 00 _DST= "$_DST")"

		if [[ -h "$_SCR" ]]; then
			:
			#echo "# 01 Ignore Link: $_SCR"
		elif [[ -L "$_DST" ]]; then
			_OLD="$(readlink "$_DST")"

			#echo "# 02 Link already present: $(ls -1d "$_DST")"
			#echo "# 02                     : $(ls -1d "$_OLD")"
			rm "$_DST"
		fi

		if [[ -d "$_SRC" ]]; then
			#echo "# 03 Link create     SRC : $_SRC"
			#echo "# 03 Link create     DST : $_DST"

			#echo " # 03 ls -1d ${_DST}:::*"
			_TMP="$(ls -1d ${_DST}:::* 2>&-)"

			#echo "# 03 TMP             $_TMP"
			if [[ "$_TMP" == "" ]]; then
				: #echo "# 03 Link new        $_DST"
			else
				: #echo "# 03 Link EXISTS     $_DST"
			fi

			#echo "# 04 ln -s $_SRC ${_DST}:::${_U}"
			ln -s "$_SRC" "${_DST}:::${_U}"
		fi
	done

done
